site_name: SAE
theme:
  name: material
nav:
    - Home: index.md
    - Equipe: equipe.md
    - Panejamento: planejamento.md
    # - Ponto de Controle 1: controle1.md
    - Ponto de Controle 2: 
        - Analise de Tarefa: PC2/analise-tarefas.md
        - Perfil do usuario: PC2/perfil-usuarios.md
        - Persona: PC2/personas.md
    # - Ponto de Controle 3: 
    #     - Guia de Estilo: PC3/Guia de Estilo.md
    #     - Metas de usabilidade: PC3/Metas de usabilidade.md
    #     - Persona: PC3/Princípios Gerais de Projeto.md
